version: "3.5"
services:
  logcore:
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: desafio
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    ports:
      - 9999:8080
    networks:
      - desafio
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: desafio
    ports:
      - 5433:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - desafio
networks:
  desafio:
    name: desafio_network
